//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTAsema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commands
    {
        public int CommandID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string Command { get; set; }
        public bool Executed { get; set; }
    
        public virtual devices devices { get; set; }
    }
}
