//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTAsema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class measurements
    {
        public int MeasurementID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<double> Celsius { get; set; }
        public Nullable<double> Fahrenheit { get; set; }
        public Nullable<double> Humidity { get; set; }
        public string Region { get; set; }
    
        public virtual devices devices { get; set; }
    }
}
